const ACTIONS = {
	LOGIN: "LOGIN",
	LOGOUT: "LOGOUT",
	ADMIN_LOADING: "ADMIN_LOADING",
	ADMIN_LOADED: "ADMIN_LOADED",
	ADMIN_ERROR: "ADMIN_ERROR",
	GET_TOKEN: "GET_TOKEN",
	REMOVE_TOKEN: "REMOVE_TOKEN",
	GET_USER: "GET_USER",
	GET_ALL_USERS: "GET_ALL_USERS",
	GET_ERRORS: "GET_ERRORS",
	CLEAR_ERRORS: "CLEAR_ERRORS",
	PRODUCT_LOADING: "PRODUCT_LOADING",
	PRODUCT_ERROR: "PRODUCT_ERROR",
	PRODUCT_LOADED: "PRODUCT_LOADED",
	LOGIN2: "LOGIN2",
	USER_LOADING: "USER_LOADING",
	USER_LOADED: "USER_LOADED",
	USER_ERROR: "USER_ERROR",
	RECOVER_PASSWORD: "RECOVER_PASSWORD",
};

export default ACTIONS;
